### PR TITLE
Tried to add d3 to angular. Succeeded in adding Firebase to Angular.

### PR DESCRIPTION
**Pull request by teachrdan**
Still don't know how to do d3 + Firebase in Angular. It's more difficult than doing either by themselves.

### CODE REVIEW

**Comment by nsipplswezey** [comment]
Things Nick and Christine will implement Saturday:
-figure out why app/scripts/app.js has the following functions that are repeated in datavis.js and tpm.js
countStrokes
orderData
-bind the output data objects to dom elements using d3
-render in data-view

Questions for Dan:

**Comment by teachrdan** [comment]
The stuff in app.js is functionally the same as in datavis.js , but some in
an angular controller, with slightly different input from $firebase.

**Comment by nsipplswezey** [comment]
Thanks Dan!

**Comment by nsipplswezey** [comment]
Merging this! I was able to visualize some data from the work Dan did! Awesome!

It's all in Angular and uses SVG, and it is super MVP.

As a short summary, it turns out that Angular and D3 don't really play so nice together. Why? Because they both bind data to the DOM, using completely different methods and syntax. Which means that using D3 and Angular together requires some crazy deep understanding of both of them.

Without knowing it, it seems that when we decided to use angular for our data view, we also implicitly decided that using D3 visualization was going to be really tough.

Props Dan for getting so much of the work done organizing the data so that I could grab it, play with it, and get something together. Highfive!

**Pull request merged**
