### PR TITLE
Update _CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by nsipplswezey**
Made some small changes for clarity, as I was going through these steps with a new fork.
Note for later: its unclear when I should be branching and rebasing from the upstream development branch vs from upstream master.

### CODE REVIEW

**Comment by tliber** [comment]
We should be pulling from upstream master to work on a new feature. Should only be pulling from upstream master to fix a urgent bug. Make that clear and feel free to push.

**Comment by nsipplswezey** [comment]
Tole did you mean we should be pulling from upstream **development** to work on a new feature? And we only pull from upstream **master** to fix an urgent bug?

**Comment by nsipplswezey** [comment]
To test the workflow outline in _CONTIBUTING.md, I deleted my fork, then forked Fire-Devil again, and cloned to my local machine and tried to follow the instructions.

To have access to the development branch on my local git repo I had to do a:
`git checkout -b development origin/development`

My clone only had the master branch available locally

```
Nicolass-MacBook-Air:Experiment nsipplsw$ git clone https://github.com/nsipplswezey/Fire-Devil.git
Cloning into 'Fire-Devil'...
remote: Counting objects: 376, done.
remote: Compressing objects: 100% (279/279), done.
remote: Total 376 (delta 179), reused 184 (delta 73)
Receiving objects: 100% (376/376), 160.61 KiB | 258.00 KiB/s, done.
Resolving deltas: 100% (179/179), done.
Checking connectivity... done.

Nicolass-MacBook-Air:Experiment nsipplsw$ cd Fire-Devil/

Nicolass-MacBook-Air:Fire-Devil nsipplsw$ git branch
* master
```

So then I did the `git checkout -b development origin/development`
And now I have my local development branch set up I think.
I'm going to try to make a pull request from this branch, with the heroku deployment configuration stuff, and see if it works.

```
Nicolass-MacBook-Air:Fire-Devil nsipplsw$ git checkout -b development origin/development
Branch development set up to track remote branch development from origin.
Switched to a new branch 'development'

Nicolass-MacBook-Air:Fire-Devil nsipplsw$ git branch
* development
  master
```

**Comment by nsipplswezey** [comment]
Whoah! I just added 3 lines to allow the master branch to be deployed. And because I already had an open pull request, it added the commit to this pull request! Cool!

The new "Adds configuration for deployment" commit allows our master branch to be deployed using `git push heroku master` from your local repo, as long as its up to date with the upstream master.

Dan + me's data-view visualization isn't merged into the master yet, so data-view is still empty.

And the development branch is current undeployable because of an auth issue.

**Comment by nsipplswezey** [comment]
Whoah! I just added 3 lines to allow the master branch to be deployed. And because I already had an open pull request, it added the commit to this pull request! Cool!

The new "Adds configuration for deployment" commit allows our master branch to be deployed using ```git push heroku master``` from your local repo, as long as its up to date with the upstream master.

Dan + me's data-view visualization isn't merged into the master yet, so data-view is still empty.

And the development branch is current undeployable because of an auth issue.

**Comment by nsipplswezey** [comment]
Whoah! I just added 3 lines to allow the master branch to be deployed. And because I already had an open pull request, it added the commit to this pull request! Cool!

The new "Adds configuration for deployment" commit allows our master branch to be deployed using ```git push heroku master``` from your local repo, as long as its up to date with the upstream master.

Dan + me's data-view visualization isn't merged into the master yet, so data-view is still empty.

And the development branch is current undeployable because of an auth issue.

**Comment by nsipplswezey** [comment]
Whoah! I just added 3 lines to allow the master branch to be deployed. And because I already had an open pull request, it added the commit to this pull request! Cool!

The new "Adds configuration for deployment" commit allows our master branch to be deployed using ```git push heroku master``` from your local repo, as long as its up to date with the upstream master.

Dan + me's data-view visualization isn't merged into the master yet, so data-view is still empty.

And the development branch is current undeployable because of an auth issue.

**Comment by nsipplswezey** [comment]
Whoah! I just added 3 lines to allow the master branch to be deployed. And because I already had an open pull request, it added the commit to this pull request! Cool!

The new "Adds configuration for deployment" commit allows our master branch to be deployed using ```git push heroku master``` from your local repo, as long as its up to date with the upstream master.

Dan + me's data-view visualization isn't merged into the master yet, so data-view is still empty.

And the development branch is current undeployable because of an auth issue.

**Comment by tliber** [comment]
Ok, then I guess we have no choice but to push the auth.js file. Feel free to delete it from .gitignore and if should push on it's own. And yes Nick thanks for catching my error. SInce you tested the remaining workflow pull the request after. Thank you.

**Pull request merged**
